version: "3"

services:
  gpt-telegram-bot:
    image: dimasorik/gpt-4-telegram-bot:1.0.0
    environment:
      - TELEGRAM_TOKEN=<FILL_ME_IN>
      - OPENAI_TOKEN=<FILL_ME_IN>
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
    networks:
      - webnet

networks:
  webnet: