version: "3"

services:
  gpt-telegram-bot:
    image: europe-west4-docker.pkg.dev/telegram-gpt-pot/docker-hub/gpt4-telegram-bot:1.0.2
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 512M
        reservations:
          cpus: "1"
          memory: 256M
    ports: 
      - "8000:8000"
    networks:
      - webnet

networks:
  webnet: